openapi: 3.0.0
info:
  version: 0.0.1
  title: WoW Classic Item API
servers:
  - url: http://localhost:8080
    description: Development Machine
paths:
  /items:
    get:
      summary: returns a list of items by given filter
      operationId: findItems
      tags:
        - items
      parameters:
        - $ref: '#/components/parameters/OptionalOwn'
          required: false
        - $ref: '#/components/parameters/Slots'
      responses:
        200:
          $ref: '#/components/responses/Items'
  /items/own:
    get:
      summary: updates the own state of the item
      operationId: setOwn
      tags:
        - items
      parameters:
        - $ref: '#/components/parameters/Id'
        - $ref: '#/components/parameters/Own'
      responses:
        201:
          description: 'updated'
components:
  parameters:
    Id:
      name: id
      in: query
      schema:
        type: integer
        format: int64
      required: true
    Own:
      name: own
      in: query
      schema:
        type: boolean
      required: true
    OptionalOwn:
      name: own
      in: query
      schema:
        type: boolean
      required: false
    Slots:
      name: slots
      in: query
      schema:
        type: array
        items:
          $ref: '#/components/schemas/Slots'
  responses:
    OK:
      description: standard ok message
    Items:
      description: a list of items
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Item'
  schemas:
    Slots:
      type: string
      enum:
        - HEAD
        - NECK
        - SHOULDERS
        - BACK
        - CHEST
        - WRIST
        - LEGS
        - HAND
        - WAIST
        - FEET
        - RING
        - TRINKET
        - MAINHAND
        - OFFHAND
        - WARD]
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int32
        slot:
          $ref: '#/components/schemas/Slots'
        name:
          type: string
        wowHeadId:
          type: integer
          format: int32
        source:
          $ref: '#/components/schemas/Source'
        own:
          type: boolean
    Source:
      type: object
      properties:
        type:
          type: string
        location:
          type: string
        target:
          type: string
        wowHeadId:
          type: integer
          format: int32
